require 'spaceship'
Spaceship::ConnectAPI::App.const_set('ESSENTIAL_INCLUDES', 'appStoreVersions')

lane :build do
    app_store_connect_api_key(
      "key_id": ENV["KEY_ID"],
      "issuer_id": ENV["APP_STORE_CONNECT_ISSUER_ID"],
      "key_content": ENV["API_KEY"],
      "is_key_content_base64": true,
      duration: 1200,
      in_house: false,
      verbose: true
    )
    match(
      type: "appstore",
      app_identifier: ENV["APP_IDENTIFIER"],
      username: ENV["APPLE_DEVELOPER_USERNAME"],
      team_id: ENV["TEAM_ID"]
    )
    increment_build_number(build_number: ENV["BUILD_ID"])
    gym(project: "HelloWorld.xcodeproj")
  end
lane :test do
    scan(project: "HelloWorld.xcodeproj",
              devices: ["iPhone Xs"])
  end
lane :beta do
  api_key = app_store_connect_api_key(
    key_id: ENV["KEY_ID"],
    issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
    key_content: ENV["API_KEY"],
    duration: 1200,
    in_house: false,
    is_key_content_base64: true,
  )
  pilot(
    api_key: api_key,
  )
  end
